build: false
environment:
    PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6.3"
    PYTHON_ARCH: "64"
    
    CONAN_UPLOAD: "https://conan.campar.in.tum.de"
    CONAN_REMOTES: "https://conan.campar.in.tum.de, https://api.bintray.com/conan/bincrafters/public-conan"
    CONAN_REFERENCE: "ubitrack_core/1.3.0"
    CONAN_USERNAME: "ubitrack"
    CONAN_CHANNEL: "stable"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15


install:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory

test_script:
  - python build.py
